name: Unity GameCI Template 🎮

on:
  push:
    branches:
      - main

# env:
#   UNITY_LICENSE: ${{ secrets.UNITY_CODE_YEAH }}
#   UNITY_EMAIL: ${{ secrets.XANDER_EMAIL }}
#   UNITY_PASSWORD: ${{ secrets.XANDER_PASSWORD }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0.3
        env:
          UNITY_EMAIL: ${{ secrets.XANDER_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.XANDER_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_CODE_YEAH }}
        with:
          projectPath: ../..
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        id: myBuildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_CODE_YEAH }}
          UNITY_EMAIL: ${{ secrets.XANDER_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.XANDER_PASSWORD }}
        with:
          versioning: Semantic
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
